// Mocks generated by Mockito 5.4.6 from annotations
// in pokedex_app/test/controllers/pokemon_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex_app/models/pokemon.dart' as _i5;
import 'package:pokedex_app/models/pokemon_detail.dart' as _i2;
import 'package:pokedex_app/services/api_services.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePokemonDetail_0 extends _i1.SmartFake implements _i2.PokemonDetail {
  _FakePokemonDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvolutionChain_1 extends _i1.SmartFake
    implements _i2.EvolutionChain {
  _FakeEvolutionChain_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServices extends _i1.Mock implements _i3.ApiServices {
  MockApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Pokemon>> fetchPokemon(int? offset, int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemon, [offset, limit]),
            returnValue: _i4.Future<List<_i5.Pokemon>>.value(<_i5.Pokemon>[]),
          )
          as _i4.Future<List<_i5.Pokemon>>);

  @override
  _i4.Future<_i2.PokemonDetail> fetchPokemonDetail(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemonDetail, [url]),
            returnValue: _i4.Future<_i2.PokemonDetail>.value(
              _FakePokemonDetail_0(
                this,
                Invocation.method(#fetchPokemonDetail, [url]),
              ),
            ),
          )
          as _i4.Future<_i2.PokemonDetail>);

  @override
  _i4.Future<void> prefetchPokemonDetails(List<_i5.Pokemon>? pokemonList) =>
      (super.noSuchMethod(
            Invocation.method(#prefetchPokemonDetails, [pokemonList]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.EvolutionChain> fetchEvolutionChain(String? speciesUrl) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEvolutionChain, [speciesUrl]),
            returnValue: _i4.Future<_i2.EvolutionChain>.value(
              _FakeEvolutionChain_1(
                this,
                Invocation.method(#fetchEvolutionChain, [speciesUrl]),
              ),
            ),
          )
          as _i4.Future<_i2.EvolutionChain>);
}
