// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGW_8x9RtGBIzgA28oNzNfh3_-2DS6HQw',
    appId: '1:130045478502:web:7aae14140cc5c012760fa7',
    messagingSenderId: '130045478502',
    projectId: 'pokedex-b50a3',
    authDomain: 'pokedex-b50a3.firebaseapp.com',
    storageBucket: 'pokedex-b50a3.firebasestorage.app',
    measurementId: 'G-QHETZTZYYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEFktM3yXeRoH1bZmaFZgzwt4g1iWdsDA',
    appId: '1:130045478502:android:940636f99a7230e9760fa7',
    messagingSenderId: '130045478502',
    projectId: 'pokedex-b50a3',
    storageBucket: 'pokedex-b50a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOjrAP0W6JI0MGWterEk9bCzbBI9gGfvQ',
    appId: '1:130045478502:ios:9db2ceaa83189c5e760fa7',
    messagingSenderId: '130045478502',
    projectId: 'pokedex-b50a3',
    storageBucket: 'pokedex-b50a3.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOjrAP0W6JI0MGWterEk9bCzbBI9gGfvQ',
    appId: '1:130045478502:ios:9db2ceaa83189c5e760fa7',
    messagingSenderId: '130045478502',
    projectId: 'pokedex-b50a3',
    storageBucket: 'pokedex-b50a3.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGW_8x9RtGBIzgA28oNzNfh3_-2DS6HQw',
    appId: '1:130045478502:web:a4d057b1f1e758e5760fa7',
    messagingSenderId: '130045478502',
    projectId: 'pokedex-b50a3',
    authDomain: 'pokedex-b50a3.firebaseapp.com',
    storageBucket: 'pokedex-b50a3.firebasestorage.app',
    measurementId: 'G-Q4NMHJYCZD',
  );

}