// Mocks generated by Mockito 5.4.6 from annotations
// in pokedex_app/test/views/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex_app/controllers/favorites_controller.dart' as _i3;
import 'package:pokedex_app/controllers/pokemon_controller.dart' as _i6;
import 'package:pokedex_app/models/pokemon.dart' as _i4;
import 'package:pokedex_app/models/pokemon_detail.dart' as _i2;
import 'package:pokedex_app/services/api_services.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePokemonDetail_0 extends _i1.SmartFake implements _i2.PokemonDetail {
  _FakePokemonDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvolutionChain_1 extends _i1.SmartFake
    implements _i2.EvolutionChain {
  _FakeEvolutionChain_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FavoritesController].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesController extends _i1.Mock
    implements _i3.FavoritesController {
  MockFavoritesController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.Pokemon> get favorites =>
      (super.noSuchMethod(
            Invocation.getter(#favorites),
            returnValue: <_i4.Pokemon>[],
          )
          as List<_i4.Pokemon>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  bool isFavorite(_i4.Pokemon? pokemon) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [pokemon]),
            returnValue: false,
          )
          as bool);

  @override
  void toggleFavorite(_i4.Pokemon? pokemon) => super.noSuchMethod(
    Invocation.method(#toggleFavorite, [pokemon]),
    returnValueForMissingStub: null,
  );

  @override
  void addFavorite(_i4.Pokemon? pokemon) => super.noSuchMethod(
    Invocation.method(#addFavorite, [pokemon]),
    returnValueForMissingStub: null,
  );

  @override
  void removeFavorite(_i4.Pokemon? pokemon) => super.noSuchMethod(
    Invocation.method(#removeFavorite, [pokemon]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i4.Pokemon> searchFavorites(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchFavorites, [query]),
            returnValue: <_i4.Pokemon>[],
          )
          as List<_i4.Pokemon>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PokemonController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonController extends _i1.Mock implements _i6.PokemonController {
  MockPokemonController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i4.Pokemon>> fetchPokemon(int? offset, int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemon, [offset, limit]),
            returnValue: _i7.Future<List<_i4.Pokemon>>.value(<_i4.Pokemon>[]),
          )
          as _i7.Future<List<_i4.Pokemon>>);
}

/// A class which mocks [ApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServices extends _i1.Mock implements _i8.ApiServices {
  MockApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i4.Pokemon>> fetchPokemon(int? offset, int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemon, [offset, limit]),
            returnValue: _i7.Future<List<_i4.Pokemon>>.value(<_i4.Pokemon>[]),
          )
          as _i7.Future<List<_i4.Pokemon>>);

  @override
  _i7.Future<_i2.PokemonDetail> fetchPokemonDetail(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemonDetail, [url]),
            returnValue: _i7.Future<_i2.PokemonDetail>.value(
              _FakePokemonDetail_0(
                this,
                Invocation.method(#fetchPokemonDetail, [url]),
              ),
            ),
          )
          as _i7.Future<_i2.PokemonDetail>);

  @override
  _i7.Future<void> prefetchPokemonDetails(List<_i4.Pokemon>? pokemonList) =>
      (super.noSuchMethod(
            Invocation.method(#prefetchPokemonDetails, [pokemonList]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.EvolutionChain> fetchEvolutionChain(String? speciesUrl) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEvolutionChain, [speciesUrl]),
            returnValue: _i7.Future<_i2.EvolutionChain>.value(
              _FakeEvolutionChain_1(
                this,
                Invocation.method(#fetchEvolutionChain, [speciesUrl]),
              ),
            ),
          )
          as _i7.Future<_i2.EvolutionChain>);
}
