// Mocks generated by Mockito 5.4.6 from annotations
// in pokedex_app/test/mocks/generate_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i14;
import 'dart:typed_data' as _i16;

import 'package:firebase_auth/firebase_auth.dart' as _i9;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:pokedex_app/data/models/pokemon_detail_model.dart' as _i2;
import 'package:pokedex_app/data/models/pokemon_model.dart' as _i6;
import 'package:pokedex_app/data/repositories/auth_repository.dart' as _i12;
import 'package:pokedex_app/data/repositories/favorites_repository.dart'
    as _i13;
import 'package:pokedex_app/data/repositories/pokemon_repository.dart' as _i11;
import 'package:pokedex_app/data/services/api/pokemon_api_service.dart' as _i4;
import 'package:pokedex_app/data/services/firebase/auth_service.dart' as _i8;
import 'package:pokedex_app/data/services/firebase/favorites_service.dart'
    as _i10;
import 'package:pokedex_app/data/services/local/cache_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePokemonDetail_0 extends _i1.SmartFake implements _i2.PokemonDetail {
  _FakePokemonDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvolutionChain_1 extends _i1.SmartFake
    implements _i2.EvolutionChain {
  _FakeEvolutionChain_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_3 extends _i1.SmartFake
    implements _i3.StreamedResponse {
  _FakeStreamedResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PokemonApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonApiService extends _i1.Mock implements _i4.PokemonApiService {
  MockPokemonApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.Pokemon>> fetchPokemonList(int? offset, int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemonList, [offset, limit]),
            returnValue: _i5.Future<List<_i6.Pokemon>>.value(<_i6.Pokemon>[]),
          )
          as _i5.Future<List<_i6.Pokemon>>);

  @override
  _i5.Future<_i2.PokemonDetail> fetchPokemonDetail(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemonDetail, [url]),
            returnValue: _i5.Future<_i2.PokemonDetail>.value(
              _FakePokemonDetail_0(
                this,
                Invocation.method(#fetchPokemonDetail, [url]),
              ),
            ),
          )
          as _i5.Future<_i2.PokemonDetail>);

  @override
  _i5.Future<_i2.EvolutionChain> fetchEvolutionChain(String? speciesUrl) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEvolutionChain, [speciesUrl]),
            returnValue: _i5.Future<_i2.EvolutionChain>.value(
              _FakeEvolutionChain_1(
                this,
                Invocation.method(#fetchEvolutionChain, [speciesUrl]),
              ),
            ),
          )
          as _i5.Future<_i2.EvolutionChain>);

  @override
  _i5.Future<List<_i6.Pokemon>> searchPokemon(
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPokemon, [query], {#limit: limit}),
            returnValue: _i5.Future<List<_i6.Pokemon>>.value(<_i6.Pokemon>[]),
          )
          as _i5.Future<List<_i6.Pokemon>>);
}

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i7.CacheService {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonDetail? getDetailFromCache(String? url) =>
      (super.noSuchMethod(Invocation.method(#getDetailFromCache, [url]))
          as _i2.PokemonDetail?);

  @override
  void cacheDetail(String? url, _i2.PokemonDetail? detail) =>
      super.noSuchMethod(
        Invocation.method(#cacheDetail, [url, detail]),
        returnValueForMissingStub: null,
      );

  @override
  bool hasDetailInCache(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#hasDetailInCache, [url]),
            returnValue: false,
          )
          as bool);

  @override
  _i2.EvolutionChain? getEvolutionFromCache(String? speciesUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getEvolutionFromCache, [speciesUrl]),
          )
          as _i2.EvolutionChain?);

  @override
  void cacheEvolution(String? speciesUrl, _i2.EvolutionChain? chain) =>
      super.noSuchMethod(
        Invocation.method(#cacheEvolution, [speciesUrl, chain]),
        returnValueForMissingStub: null,
      );

  @override
  bool hasEvolutionInCache(String? speciesUrl) =>
      (super.noSuchMethod(
            Invocation.method(#hasEvolutionInCache, [speciesUrl]),
            returnValue: false,
          )
          as bool);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearDetailCache() => super.noSuchMethod(
    Invocation.method(#clearDetailCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearEvolutionCache() => super.noSuchMethod(
    Invocation.method(#clearEvolutionCache, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i8.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i9.User?> get userStream =>
      (super.noSuchMethod(
            Invocation.getter(#userStream),
            returnValue: _i5.Stream<_i9.User?>.empty(),
          )
          as _i5.Stream<_i9.User?>);

  @override
  _i5.Future<_i9.User?> signUp(String? email, String? password, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [email, password, name]),
            returnValue: _i5.Future<_i9.User?>.value(),
          )
          as _i5.Future<_i9.User?>);

  @override
  _i5.Future<_i9.User?> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i5.Future<_i9.User?>.value(),
          )
          as _i5.Future<_i9.User?>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i9.User?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<_i9.User?>.value(),
          )
          as _i5.Future<_i9.User?>);

  @override
  _i5.Future<void> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [FavoritesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesService extends _i1.Mock implements _i10.FavoritesService {
  MockFavoritesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> addFavorite(_i6.Pokemon? pokemon) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [pokemon]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeFavorite(String? pokemonId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavorite, [pokemonId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.Pokemon>> getFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, []),
            returnValue: _i5.Future<List<_i6.Pokemon>>.value(<_i6.Pokemon>[]),
          )
          as _i5.Future<List<_i6.Pokemon>>);

  @override
  _i5.Stream<List<_i6.Pokemon>> favoritesStream() =>
      (super.noSuchMethod(
            Invocation.method(#favoritesStream, []),
            returnValue: _i5.Stream<List<_i6.Pokemon>>.empty(),
          )
          as _i5.Stream<List<_i6.Pokemon>>);

  @override
  _i5.Future<bool> isFavorite(String? pokemonId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [pokemonId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> clearAllFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllFavorites, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i11.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.Pokemon>> fetchPokemonList(int? offset, int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemonList, [offset, limit]),
            returnValue: _i5.Future<List<_i6.Pokemon>>.value(<_i6.Pokemon>[]),
          )
          as _i5.Future<List<_i6.Pokemon>>);

  @override
  _i5.Future<_i2.PokemonDetail> fetchPokemonDetail(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemonDetail, [url]),
            returnValue: _i5.Future<_i2.PokemonDetail>.value(
              _FakePokemonDetail_0(
                this,
                Invocation.method(#fetchPokemonDetail, [url]),
              ),
            ),
          )
          as _i5.Future<_i2.PokemonDetail>);

  @override
  _i5.Future<void> prefetchPokemonDetails(List<_i6.Pokemon>? pokemonList) =>
      (super.noSuchMethod(
            Invocation.method(#prefetchPokemonDetails, [pokemonList]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.EvolutionChain> fetchEvolutionChain(String? speciesUrl) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEvolutionChain, [speciesUrl]),
            returnValue: _i5.Future<_i2.EvolutionChain>.value(
              _FakeEvolutionChain_1(
                this,
                Invocation.method(#fetchEvolutionChain, [speciesUrl]),
              ),
            ),
          )
          as _i5.Future<_i2.EvolutionChain>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i6.Pokemon>> searchPokemon(
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPokemon, [query], {#limit: limit}),
            returnValue: _i5.Future<List<_i6.Pokemon>>.value(<_i6.Pokemon>[]),
          )
          as _i5.Future<List<_i6.Pokemon>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i12.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i9.User?> get userStream =>
      (super.noSuchMethod(
            Invocation.getter(#userStream),
            returnValue: _i5.Stream<_i9.User?>.empty(),
          )
          as _i5.Stream<_i9.User?>);

  @override
  _i5.Future<_i9.User?> signUp(String? email, String? password, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [email, password, name]),
            returnValue: _i5.Future<_i9.User?>.value(),
          )
          as _i5.Future<_i9.User?>);

  @override
  _i5.Future<_i9.User?> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i5.Future<_i9.User?>.value(),
          )
          as _i5.Future<_i9.User?>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i9.User?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<_i9.User?>.value(),
          )
          as _i5.Future<_i9.User?>);

  @override
  _i5.Future<void> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [FavoritesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesRepository extends _i1.Mock
    implements _i13.FavoritesRepository {
  MockFavoritesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> addFavorite(_i6.Pokemon? pokemon) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [pokemon]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeFavorite(String? pokemonId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavorite, [pokemonId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.Pokemon>> getFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, []),
            returnValue: _i5.Future<List<_i6.Pokemon>>.value(<_i6.Pokemon>[]),
          )
          as _i5.Future<List<_i6.Pokemon>>);

  @override
  _i5.Stream<List<_i6.Pokemon>> favoritesStream() =>
      (super.noSuchMethod(
            Invocation.method(#favoritesStream, []),
            returnValue: _i5.Stream<List<_i6.Pokemon>>.empty(),
          )
          as _i5.Stream<List<_i6.Pokemon>>);

  @override
  _i5.Future<bool> isFavorite(String? pokemonId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [pokemonId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> clearAllFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllFavorites, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i3.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i5.Future<_i3.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i5.Future<_i3.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i14.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i3.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i14.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i3.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i14.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i3.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i14.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i3.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.Response>);

  @override
  _i5.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i5.Future<String>.value(
              _i15.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i16.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i5.Future<_i16.Uint8List>.value(_i16.Uint8List(0)),
          )
          as _i5.Future<_i16.Uint8List>);

  @override
  _i5.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i5.Future<_i3.StreamedResponse>.value(
              _FakeStreamedResponse_3(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i5.Future<_i3.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
